### ISSUE TITLE
Bug/Feature enhancements required

### ISSUE THREAD

**Issue by Vishal643** [ajayahara/JIOMART.COM_RCT_201#33]
- [x] On reloading any page it is showing `page not found error` so work on it and fix it.
- [x] You need to work on UI part a lot. None of the carousels are visible properly. User needs to give an attention that there is a carousel.
- [x] On clicking carousel you should not be redirecting to the `products` page instead it should work like a carousel.
- [x] It does not looks like you are having any actions on any product the `cursor` state is not expected. It should ideally be `pointer` when you hover over any product.
- [x] You haven't used redux properly all the API calls should go in actions of the redux and you are individually using them in the respective components. So use the redux properly with all the API calls to the respective actions.
- [x] Why there are items in the cart by default, adding the items to the cart is not working, you should not hardcode the data in the cart use the proper way `Add To Cart` feature should work. 
- [x] Also increment and decrement items in cart is not working.
- [x] If a user is not filling the address still he is able to go the checkout page, so make it proper, without necessary data given user should not be going to checkout page.
- [x] Work on the alignments of buttons and text on `checkout` and `cart page`.
- [x] Last but not the least github-commits the commit titles are not at all meaning full. What is `ajay`, `done` etc. These should be like
- [x] if it is feature the commit should go like this feat("small title of feature") => representing feature :- feat("signup on checkout page")
- [x]  Another thing is on the tab you are still showing React App change it based on the page you are navigating. You can easily do that by setting the title in first render of the component.

**Comment by ajayahara** [comment]
5 bugs resolved

**Comment by CodexPuneet** [comment]
Fixed all the issues..
