### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mansisindhu** [ajayahara/JIOMART.COM_RCT_201#34]
- In the landing page only 2-3 folds have content/images, the rest of the page is blank and empty (at first load, the website is very slow).
- UI is breaking in many places
- Images are shrinking in landing page and other places
- Website is not responsive
- Search box is not working
- Infinite loop is going in this api call https://kiwi-discovered-pyjama.glitch.me/cart in cart page
- Can’t increase and decrease the quantity of items in cart 
- Was able to checkout without adding delivery address, this should not happen
- After login still can see the login modal, this should not be happening
- Lot of commented code

**Comment by ajayahara** [comment]
3  task  solved

**Comment by CodexPuneet** [comment]
Fixed All the Issues

**Comment by CodexPuneet** [comment]
Fixed All the Issues
